language: python
python:
    - "2.6"
    - "2.7"
env:
    - DJANGO=1.3 APPS=
    - DJANGO=1.4 APPS=
    - DJANGO=1.5 APPS=
    - DJANGO=1.6 APPS="-a south"
install:
    - pip install -q Django==$DJANGO --use-mirrors
    - pip install South --use-mirrors
script:
    - python bin/fish_django_completions.py $APPS
